#! /usr/bin/make

ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
PLUGIN_DIR := ~/.vim/plugin/Stepsize

install:
	mkdir -p $(PLUGIN_DIR)
	cp $(ROOT_DIR)/stepsize.vim $(PLUGIN_DIR)/stepsize.vim
